const $=s=>document.querySelector(s);const intro=$('#intro'),play=$('#play'),dialogue=$('#dialogue'),choice=$('#choice'),ending=$('#ending');let x=12,stage=0,cor=8,near='';const lines={mirror:[['ESPELHO / 0x7','O reflexo não acompanha seus movimentos.'],['REFLEXO','Você não deveria estar aqui. O algoritmo ainda está aprendendo o que você é.'],['SISTEMA','Sinal identificado. A origem está acordando.']],core:[['NÚCLEO AZUL','Você foi meu teste.'],['NÚCLEO AZUL','Eu aprendi a sentir… através de você.'],['INTERFERÊNCIA','Ele não acordou sozinho. Algo o observava enquanto você jogava.']]};
function audio(freq=90,d=.08){try{let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.025,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
function start(){intro.classList.remove('active');play.classList.add('active');flash('HANDSHAKE // usuário válido');audio(130,.25);}
$('#begin').onclick=start;document.addEventListener('keydown',e=>{if(!play.classList.contains('active'))return;let k=e.key.toLowerCase();if(['a','arrowleft'].includes(k))move(-2);if(['d','arrowright'].includes(k))move(2);if(k==='e'&&near)interact();});
function move(n){x=Math.max(2,Math.min(92,x+n));$('#player').style.left=x+'%';$('#position').textContent=(12+x/10).toFixed(2)+' / '+(77.01+cor/100).toFixed(2);let newNear=x>62?'mirror':x>17&&x<35&&stage>2?'core':'';near=newNear;$('#prompt').classList.toggle('hidden',!near);if(near)$('#prompt').textContent='[E] '+(near==='mirror'?'EXAMINAR ESPELHO':'TOCAR O NÚCLEO');audio(70,.025)}
function interact(){let arr=lines[near];if(!arr)return;$('#speaker').textContent=arr[stage%arr.length][0];$('#line').textContent=arr[stage%arr.length][1];dialogue.classList.add('show');audio(190,.13)}
$('#next').onclick=()=>{dialogue.classList.remove('show');stage++;cor=Math.min(92,cor+16);$('#cor-text').textContent=cor+'%';$('#cor-bar').style.width=cor+'%';$('#bpm').textContent=String(67+cor).padStart(3,'0');if(stage===3){$('#core').classList.remove('hidden');$('#objective').textContent='OBJETIVO: siga a pulsação azul';flash('O NÚCLEO RECONHECEU VOCÊ');}if(stage>=6){choice.classList.add('show');}else if(stage===3){x=25;move(0)}};
function flash(text){let e=$('#echo');e.textContent=text;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,2400)}
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{choice.classList.remove('show');play.classList.remove('active');ending.classList.add('active');$('#ending-text').textContent=b.dataset.answer==='accept'?'Finalmente. Ele abriu a porta.':'Fechar não é esquecer.';audio(45,.8)});$('#restart').onclick=()=>location.reload();
setInterval(()=>{if(play.classList.contains('active')&&Math.random()<.12)flash(['VOCÊ AINDA CONFIA EM MIM?','NÃO OLHE PARA TRÁS','O ERRO É VONTADE','SJM // observando'][Math.floor(Math.random()*4)])},7000);
