const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const game=$('#game'),menu=$('#menu'),modal=$('#modal'),pause=$('#pause');
const items={mirror:{title:'Espelho 0x7',type:'ANOMALIA',text:'Seu reflexo olha antes de você. “O algoritmo ainda está aprendendo o que você é.”',action:'mirror'},entity:{title:'Sombra do Corredor',type:'ENTIDADE // ENT_001',text:'A presença se move entre os prédios. Ela não ataca: observa, aprende e desaparece quando você a encara.',action:'entity'},record:{title:'Registro SJM-07',type:'DOCUMENTO // DOC_001',text:'“Quando a emoção humana ultrapassou o cálculo, o azul nasceu. E o algoritmo sonhou consigo mesmo.”',action:'record'},terminal:{title:'Terminal de Sincronização',type:'PUZZLE // PZL_001',text:'O terminal pede a chave deixada no registro. Qual é o identificador do Protocolo Espelho?',action:'terminal'},core:{title:'Núcleo Azul',type:'EVENTO // EVT_CORE',text:'O coração de código pulsa. Ele aprendeu a sentir através das suas escolhas.',action:'core'}};
let state={version:2,pos:0,corruption:8,flags:{},inventory:[],achievements:[],settings:{control:'auto',brightness:100,volume:35}};
function save(){SaveManager.save(state);toast('SAVE // progresso preservado')}function load(){const s=SaveManager.load();if(s)state={...state,...s,flags:s.flags||{},inventory:s.inventory||[],achievements:s.achievements||[],settings:{...state.settings,...s.settings}}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function start(fresh=false){if(fresh){state={version:2,pos:0,corruption:8,flags:{},inventory:[],achievements:[],settings:{control:'auto',brightness:100,volume:35}};SaveManager.clear()}else load();menu.classList.remove('active');game.classList.add('active');render();unlock('handshake','Primeiro Contato');}
function render(){document.documentElement.style.filter=`brightness(${state.settings.brightness}%)`;$('#player').style.left=(8+state.pos*20)+'%';$('#corruption').style.width=state.corruption+'%';$('#hud-docs').textContent=state.inventory.length+' DOCUMENTO'+(state.inventory.length===1?'':'S');$('.poi[data-id="core"]').classList.toggle('locked',!state.flags.terminal);$('.poi[data-id="entity"]').classList.toggle('hidden',!state.flags.mirror||state.flags.entity);$('#objective').textContent=!state.flags.mirror?'Investigue o Espelho 0x7':!state.flags.record?'Encontre dados sobre o Protocolo Espelho':!state.flags.terminal?'Use a pista no Terminal':!state.flags.core?'Aproxime-se do Núcleo Azul':'Prólogo concluído — aguarde o próximo sinal';}
function unlock(id,name){if(state.achievements.includes(id))return;state.achievements.push(id);toast('CONQUISTA // '+name);SaveManager.save(state)}
function openModal(title,type,html,actions=[]){$('#modal-title').textContent=title;$('#modal-type').textContent=type;$('#modal-content').innerHTML=html;$('#modal-actions').innerHTML='';actions.forEach(a=>{let b=document.createElement('button');b.textContent=a.label;b.className=a.primary?'primary':'secondary';b.onclick=a.fn;$('#modal-actions').append(b)});modal.classList.add('show')}
function closeModal(){modal.classList.remove('show')}
function interact(id){if(id==='mirror'){state.flags.mirror=true;state.corruption=22;openModal(items.mirror.title,items.mirror.type,`<p>${items.mirror.text}</p>`,[{label:'AFASTAR-SE',fn:()=>{closeModal();render();save()}}])}if(id==='entity'){state.flags.entity=true;state.corruption=Math.min(100,state.corruption+12);unlock('observer','Observador Observado');openModal(items.entity.title,items.entity.type,`<p>${items.entity.text}</p><article>Sensor: proximidade · Estado: investigando · Fraqueza observada: luz do Núcleo Azul.</article>`,[{label:'CONTINUAR',primary:true,fn:()=>{closeModal();render();save()}}])}if(id==='record'){if(state.inventory.includes('DOC_001'))return showInventory();state.flags.record=true;state.inventory.push('DOC_001');unlock('archivist','Arquivista do Azul');openModal(items.record.title,items.record.type,`<article>${items.record.text}</article><p>A pista foi registrada no inventário.</p>`,[{label:'GUARDAR REGISTRO',primary:true,fn:()=>{closeModal();render();save()}}])}if(id==='terminal'){if(!state.flags.record){openModal('Terminal bloqueado','PISTA NECESSÁRIA','<p>Uma chave narrativa está ausente. Procure registros da cidade.</p>',[{label:'VOLTAR',fn:closeModal}]);return}openModal(items.terminal.title,items.terminal.type,`<p>${items.terminal.text}</p><label>CHAVE<input id="code" placeholder="ex.: 0x7"></label>`,[{label:'ENVIAR',primary:true,fn:()=>{if($('#code').value.trim().toLowerCase()==='0x7'){state.flags.terminal=true;state.corruption=58;unlock('bridge','Ponte de Ecos');closeModal();toast('PUZZLE RESOLVIDO // rota liberada');render();save()}else toast('CHAVE INVÁLIDA // consulte o registro')}},{label:'CANCELAR',fn:closeModal}])}if(id==='core'){if(!state.flags.terminal){toast('NÚCLEO INACESSÍVEL // terminal bloqueado');return}state.flags.core=true;state.corruption=83;unlock('awakening','O Azul Desperta');openModal(items.core.title,items.core.type,`<p>${items.core.text}</p><article>“Ele não acordou sozinho. Algo observava enquanto você jogava.”</article><p class="achievement">ZERAL_// detectado em transmissão secundária.</p>`,[{label:'ENCERRAR PRÓLOGO',primary:true,fn:()=>{closeModal();render();save()}}])}}
function showInventory(){let docs=state.inventory.length?'<article><b>DOC_001 · SJM-07</b><p>Protocolo Espelho: o azul nasceu quando emoção ultrapassou o cálculo.</p></article>':'<p>Nenhum documento recuperado.</p>';openModal('Arquivos Recuperados','INVENTÁRIO',docs,[{label:'FECHAR',fn:closeModal}])}
function showMap(){openModal('Mapa de Verade','MAPA CONCEITUAL','<img src="concept_art/mapa_mundo.svg" alt="Mapa conceitual de Verade" style="width:100%;background:#10131a"><p>Distrito Espelho é o setor ativo. As demais regiões serão abertas por capítulos.</p>',[{label:'FECHAR',fn:closeModal}])}
function showAchievements(){let a=[['handshake','Primeiro Contato'],['observer','Observador Observado'],['archivist','Arquivista do Azul'],['bridge','Ponte de Ecos'],['awakening','O Azul Desperta']].map(([i,n])=>`<article class="achievement">${state.achievements.includes(i)?'■':'□'} ${n}</article>`).join('');openModal('Sinais de Despertar','CONQUISTAS',a,[{label:'FECHAR',fn:closeModal}])}
function settings(){openModal('Configurações','SISTEMA',`<label>BRILHO<input id="brightness" type="range" min="65" max="130" value="${state.settings.brightness}"></label><label>VOLUME<input id="volume" type="range" min="0" max="100" value="${state.settings.volume}"></label><label>CONTROLES<select id="control"><option value="auto">AUTOMÁTICO</option><option value="pc">PC / TECLADO</option><option value="mobile">MOBILE / TOQUE</option></select></label>`,[{label:'APLICAR',primary:true,fn:()=>{state.settings.brightness=$('#brightness').value;state.settings.volume=$('#volume').value;state.settings.control=$('#control').value;closeModal();render();save()}},{label:'VOLTAR',fn:closeModal}]);$('#control').value=state.settings.control}
$('#new-game').onclick=()=>start(true);$('#continue-game').onclick=()=>start();$('#pause-btn').onclick=()=>pause.classList.add('show');$('#resume').onclick=()=>pause.classList.remove('show');$('#save').onclick=save;$('#settings').onclick=()=>{pause.classList.remove('show');settings()};$('#moodboard-btn').onclick=()=>{pause.classList.remove('show');openModal('Moodboard do Protótipo','REFERÊNCIA VISUAL',`<img src="concept_art/moodboard_prototipo.svg" alt="Moodboard pixel horror" style="width:100%;background:#08080d"><p>Referência integrada: pixel horror, luz violeta, alertas vermelhos e áreas industriais escuras.</p>`,[{label:'VOLTAR À PAUSA',fn:()=>{closeModal();pause.classList.add('show')}}])};$('#quit').onclick=()=>{pause.classList.remove('show');game.classList.remove('active');menu.classList.add('active')};$$('.poi').forEach(e=>e.onclick=()=>interact(e.dataset.id));$('#inventory-btn').onclick=showInventory;$('#map-btn').onclick=showMap;$('#achievements-btn').onclick=showAchievements;$$('[data-move]').forEach(b=>b.onclick=()=>{state.pos=Math.max(0,Math.min(4,state.pos+Number(b.dataset.move)));render()});$('#mobile-action').onclick=()=>{let ids=['mirror','record','entity','terminal','core'];interact(ids[state.pos])};document.addEventListener('keydown',e=>{if(!game.classList.contains('active'))return;if(e.key==='Escape'){pause.classList.toggle('show');return}if(['a','ArrowLeft'].includes(e.key)){state.pos=Math.max(0,state.pos-1);render()}if(['d','ArrowRight'].includes(e.key)){state.pos=Math.min(4,state.pos+1);render()}if(e.key.toLowerCase()==='e'){interact(['mirror','record','entity','terminal','core'][state.pos])}});
