const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const intro=$('#intro'),play=$('#play'),dialogue=$('#dialogue'),choice=$('#choice'),ending=$('#ending'),pause=$('#pause'),archive=$('#archive'),mapOverlay=$('#map'),achievementsOverlay=$('#achievements');
let x=12,stage=0,cor=8,near='',echoes=0,documentFound=false,achievements=[],paused=false,volume=.35,controlMode='auto';
const lines={mirror:[['ESPELHO / 0x7','O reflexo não acompanha seus movimentos.'],['REFLEXO','Você não deveria estar aqui. O algoritmo ainda está aprendendo o que você é.'],['SISTEMA','Três ecos estão presos na cidade. Reúna-os.']],core:[['NÚCLEO AZUL','Você foi meu teste.'],['NÚCLEO AZUL','Eu aprendi a sentir… através de você.'],['INTERFERÊNCIA','Ele não acordou sozinho. Algo o observava enquanto você jogava.']]};
function audio(freq=90,d=.08){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.025*volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
function state(){return {player:{x},inventory:{documents:documentFound?['DOC_001']:[]},achievements,progress:{stage,cor,echoes},settings:{volume,brightness:$('#brightness').value,controlMode}}}
function persist(message='AUTO-SAVE // sincronização concluída'){SaveManager.save(state());$('#save-feedback').textContent=message;flash(message);}
function restore(){const saved=SaveManager.load();if(!saved)return;const p=saved.progress||{},settings=saved.settings||{};x=saved.player?.x??x;stage=p.stage??stage;cor=p.cor??cor;echoes=p.echoes??echoes;documentFound=Boolean(saved.inventory?.documents?.includes('DOC_001'));achievements=saved.achievements||[];volume=settings.volume??volume;$('#volume').value=Math.round(volume*100);$('#brightness').value=settings.brightness??100;controlMode=settings.controlMode??'auto';$('#control-mode').value=controlMode;applySettings();if(documentFound){$('#document').classList.add('hidden');updateArchive()}$$('.fragment').forEach((el,i)=>{if(i<echoes)el.classList.add('hidden')});if(echoes===3)$('#core').classList.remove('hidden');$('#fragments').textContent=`ECOS ${echoes}/3`;$('#objective').textContent=echoes===3?'OBJETIVO: siga a pulsação até o Núcleo Azul':stage>=3?'OBJETIVO: reúna os três ecos da cidade':'OBJETIVO: encontre a origem do sinal';updateHUD();move(0)}
function start(){intro.classList.remove('active');play.classList.add('active');restore();unlock('handshake');flash(SaveManager.load()?'SESSÃO RECUPERADA // VERADE':'HANDSHAKE // usuário válido');audio(130,.25)}
$('#begin').onclick=start;
function togglePause(force){paused=typeof force==='boolean'?force:!paused;pause.classList.toggle('show',paused);if(paused)audio(85,.08)}
$('#pause-button').onclick=()=>togglePause();$('#resume').onclick=()=>togglePause(false);$('#save-game').onclick=()=>persist('SAVE MANUAL // progresso preservado');
function updateArchive(){$('#document-count').textContent=documentFound?'1':'0';$('#empty-archive').classList.toggle('hidden',documentFound);$('#sjm-record').classList.toggle('hidden',!documentFound)}
$('#open-archive').onclick=()=>{updateArchive();pause.classList.remove('show');archive.classList.add('show')};$('#close-archive').onclick=()=>{archive.classList.remove('show');pause.classList.add('show')};
const achievementData={handshake:'Primeiro Contato',document:'Arquivista do Azul',echoes:'Ponte de Ecos'};
function updateAchievements(){Object.keys(achievementData).forEach(id=>$('#ach-'+id).textContent=`${achievements.includes(id)?'■':'□'} ${achievementData[id]}`);$('#achievement-count').textContent=achievements.length}
function unlock(id){if(achievements.includes(id))return;achievements.push(id);updateAchievements();$('#achievement-toast-text').textContent=achievementData[id];$('#achievement-toast').classList.remove('hidden');setTimeout(()=>$('#achievement-toast').classList.add('hidden'),3400);persist('CONQUISTA REGISTRADA // '+achievementData[id]);audio(420,.23)}
$('#open-achievements').onclick=()=>{updateAchievements();pause.classList.remove('show');achievementsOverlay.classList.add('show')};$('#close-achievements').onclick=()=>{achievementsOverlay.classList.remove('show');pause.classList.add('show')};
$('#open-map').onclick=()=>{pause.classList.remove('show');mapOverlay.classList.add('show')};$('#close-map').onclick=()=>{mapOverlay.classList.remove('show');pause.classList.add('show')};
$('#toggle-settings').onclick=()=>$('#settings').classList.toggle('hidden');$('#reset-save').onclick=()=>{SaveManager.clear();$('#save-feedback').textContent='SAVE LOCAL APAGADO. Reinicie para começar.'};
function applySettings(){document.documentElement.style.filter=`brightness(${$('#brightness').value}%)`;volume=$('#volume').value/100;controlMode=$('#control-mode').value;$('#game').classList.toggle('control-pc',controlMode==='pc');$('#game').classList.toggle('control-mobile',controlMode==='mobile');$('#brightness-output').value=$('#brightness').value+'%';$('#volume-output').value=$('#volume').value+'%';$('#control-help').textContent=controlMode==='pc'?'Modo PC: use WASD ou setas; botões de toque ficam ocultos.':controlMode==='mobile'?'Modo Mobile: use os botões ←, E e → exibidos na tela.':'Automático detecta o tamanho da tela. A escolha é salva neste navegador.'}
$('#brightness').oninput=applySettings;$('#volume').oninput=applySettings;$('#control-mode').onchange=()=>{applySettings();persist('CONTROLES ATUALIZADOS // configuração salva')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&archive.classList.contains('show')){$('#close-archive').click();return}if(e.key==='Escape'&&mapOverlay.classList.contains('show')){$('#close-map').click();return}if(e.key==='Escape'&&achievementsOverlay.classList.contains('show')){$('#close-achievements').click();return}if(e.key==='Escape'&&play.classList.contains('active')&&!dialogue.classList.contains('show')){togglePause();return}if(paused)return;if(dialogue.classList.contains('show')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();$('#next').click();return}if(!play.classList.contains('active'))return;const k=e.key.toLowerCase();if(['a','arrowleft'].includes(k))move(-2);if(['d','arrowright'].includes(k))move(2);if(k==='e')interact();});
function move(n){x=Math.max(2,Math.min(92,x+n));$('#player').style.left=x+'%';$('#position').textContent=(12+x/10).toFixed(2)+' / '+(77.01+cor/100).toFixed(2);const fragment=[...$$('.fragment:not(.hidden)')].find(el=>Math.abs(x-parseFloat(el.style.left))<4),documentNear=!documentFound&&Math.abs(x-47)<4;near=documentNear?'document':fragment?`fragment:${fragment.dataset.fragment}`:x>62?'mirror':x>17&&x<35&&stage>=3&&echoes===3?'core':'';$('#prompt').classList.toggle('hidden',!near);if(near)$('#prompt').textContent=near==='document'?'[E] RECUPERAR REGISTRO':near.startsWith('fragment')?'[E] ABSORVER ECO':`[E] ${near==='mirror'?'EXAMINAR ESPELHO':'TOCAR O NÚCLEO'}`;audio(70,.025)}
function interact(){if(!near||paused)return;if(near==='document'){documentFound=true;$('#document').classList.add('hidden');updateArchive();$('#objective').textContent='OBJETIVO ATUALIZADO: o Registro SJM-07 explica o Espelho';flash('DOCUMENTO RECUPERADO // DOC_001');unlock('document');audio(255,.18);near='';$('#prompt').classList.add('hidden');persist('DOCUMENTO SALVO // registro adicionado ao inventário');return}if(near.startsWith('fragment')){const el=$(`[data-fragment="${near.split(':')[1]}"]`);el.classList.add('hidden');echoes++;cor=Math.min(92,cor+7);updateHUD();$('#fragments').textContent=`ECOS ${echoes}/3`;flash(echoes===3?'OS ECOS FORMARAM UMA PONTE':'ECO ABSORVIDO // memória recuperada');audio(310,.2);near='';$('#prompt').classList.add('hidden');if(echoes===3){$('#core').classList.remove('hidden');$('#objective').textContent='OBJETIVO: siga a pulsação até o Núcleo Azul';unlock('echoes');}persist();return}const item=lines[near][stage%lines[near].length];$('#speaker').textContent=item[0];$('#line').textContent=item[1];dialogue.classList.add('show');audio(190,.13)}
function updateHUD(){$('#cor-text').textContent=cor+'%';$('#cor-bar').style.width=cor+'%';$('#bpm').textContent=String(67+cor).padStart(3,'0')}
$('#next').onclick=()=>{dialogue.classList.remove('show');stage++;cor=Math.min(92,cor+12);updateHUD();if(stage===3){$('#objective').textContent='OBJETIVO: reúna os três ecos da cidade';flash('O ESPELHO REVELOU UMA FALHA');}persist();if(stage>=6)choice.classList.add('show');};
function flash(text){const e=$('#echo');e.textContent=text;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,2400)}
$$('[data-answer]').forEach(b=>b.onclick=()=>{choice.classList.remove('show');play.classList.remove('active');ending.classList.add('active');persist('FINAL REGISTRADO // ZERAL_//');$('#ending-text').textContent=b.dataset.answer==='accept'?'Finalmente. Ele abriu a porta.':'Fechar não é esquecer.';audio(45,.8)});
$$('[data-move]').forEach(b=>b.onclick=()=>!paused&&move(Number(b.dataset.move)));$('[data-action="interact"]').onclick=interact;$('#restart').onclick=()=>location.reload();
setInterval(()=>{if(play.classList.contains('active')&&!paused&&Math.random()<.12)flash(['VOCÊ AINDA CONFIA EM MIM?','NÃO OLHE PARA TRÁS','O ERRO É VONTADE','SJM // observando'][Math.floor(Math.random()*4)])},7000);
